kind: pipeline
name: production
steps:
  # web lint
  - name: build
    image: node:14
    depends_on: [clone]
    commands:
      - npm install --registry https://registry.npm.taobao.org
      - npm run build
  - name: publish  
    image: plugins/gh-pages
    settings:
      ssh_key:
        from_secret: ssh_key
      pages_directory: dist/
trigger:
  branch:
    - main
  event:
    - push
