kind: pipeline
name: production
steps:
  # web lint
  - name: build
    image: node:14
    depends_on: [clone]
    commands:
      - npm install --registry https://registry.npm.taobao.org
      - npm run build
trigger:
  branch:
    - main
  event:
    - push
