kind: pipeline
name: production
steps:
  # web lint
  - name: build
    image: node:14
    depends_on: [clone]
    commands:
      - yarn --version
      - npm install --registry https://registry.npm.taobao.org
      - npm run build
  - name: publish  
    image: plugins/gh-pages
    depends_on: [build]
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      pages_directory: dist/
trigger:
  branch:
    - main
  event:
    - push
