kind: pipeline
type: docker
name: production
steps:
  # web lint
  - name: build
    image: node:14
    depends_on: [clone]
    commands:
      - git --version
      - npm ci --registry https://registry.npm.taobao.org
      - npm run build
  - name: exec
    commands:
      - ls /drone/src

trigger:
  branch:
    - main
  event:
    - push
