kind: pipeline
type: exec
name: production
steps:
  - name: test
    depends_on: [clone]
    commands:
      - docker --version
      - ls /drone/src
  # web lint
  # - name: build
  #   image: node:14
  #   depends_on: [clone]
  #   commands:
  #     - npm ci --registry https://registry.npm.taobao.org
  #     - npm run build
  # - name: publish  
  #   image: plugins/gh-pages
  #   depends_on: [build]
  #   settings:
  #     username:
  #       from_secret: username
  #     password:
  #       from_secret: password
  #     pages_directory: dist/
trigger:
  branch:
    - main
  event:
    - push
