kind: pipeline
name: api
steps:
  # web lint
  - name: web-lint
    image: node:10.15.1
    depends_on: [clone]
    commands:
      - npm install --registry https://registry.npm.taobao.org
      - npm run lint
trigger:
  branch:
    - main
  event:
    - push
