kind: pipeline
type: docker
name: production
steps:
  # web lint
  # - name: build
  #   image: node:14
  #   depends_on: [clone]
  #   commands:
  #     - git --version
  #     - npm ci --registry https://registry.npm.taobao.org
  #     - npm run build

  # - name: publish  
  #   image: plugins/gh-pages
  #   depends_on: [build]
  #   settings:
  #     username:
  #       from_secret: username
  #     password:
  #       from_secret: password
  #     pages_directory: dist/
  
  # - name: scp files
  #   image: appleboy/drone-scp
  #   depends_on: [build]
  #   settings:
  #     strip_components: 3
  #     host:
  #       from_secret: host_name
  #     user:
  #       from_secret: ssh_user
  #     password:
  #       from_secret: ssh_password
  #     port: 22
  #     command_timeout: 2m
  #     rm: true
  #     target:
  #       from_secret: target_dir
  #     source:
  #       from_secret: source_dir

trigger:
  branch:
    - main
  event:
    - push


---
kind: pipeline
type: docker
name: notify

clone:
  disable: true

depends_on: [production]

steps:
  - name: email
    image: drillster/drone-email
    settings:
      recipients: [ 1098619616@qq.com ]
      recipients_only: true
      subject: "Drone build: [{{ build.status }}] {{ repo.name }} #{{ build.number }}"
      host: smtp.163.com
      port: 465
      from:
        from_secret: email_from
      username:
        from_secret: email_user
      password:
        from_secret: email_password
      when:
        status: [ success, failure ]